AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: '0808'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: '0808'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/jachouse'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
