AZURE_LOCATION: 'eastus2'
RESOURCE_NAME_PREFIX: 'apimdemo90283'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment43535'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/jachouse'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
